services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 10
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./HawAI-backend
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=hawai
      - CORS_ORIGINS=http://localhost:5173
      - OAI_BASE_URL=http://ollama:11434/v1
      - OAI_MODEL=llava:7b
      - JWT_SECRET=change-me
    depends_on:
      - mongo
      - ollama
    ports:
      - "8000:8000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_BASE=http://localhost:8000
    command: sh -c "npm i && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
    driver: local
  ollama_data:
    driver: local


