version: "3.9"

services:
  hawai-backend:
    build: ./HawAI-backend
    container_name: hawai-backend
    ports:
      - "8000:8000"
    env_file:
      - ./HawAI-backend/.env
    depends_on:
      - ollama
      - dify-api
    networks:
      - hawai-net

  ollama:
    image: ollama/ollama:latest
    container_name: hawai-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - hawai-net

  dify-api:
    image: langgenius/dify-api:latest
    container_name: dify-api
    env_file:
      - ./dify/docker/.env
    environment:
      - PORT=5001
      - ENABLE_PLUGIN_MARKETPLACE=true
    depends_on:
      - dify-web
      - dify-db
      - dify-redis
      - dify-worker
      - dify-plugin-daemon
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:5001/health"]
      interval: 20s
      timeout: 5s
      retries: 30
    networks:
      - hawai-net

  dify-web:
    image: langgenius/dify-web:latest
    container_name: dify-web
    env_file:
      - ./dify/docker/.env
    environment:
      - PORT=3000
      - CONSOLE_API_URL=http://localhost:5001
      - NEXT_PUBLIC_CONSOLE_API_URL=http://localhost:5001
      - NEXT_PUBLIC_ENABLE_PLUGIN=true
    ports:
      - "3000:3000"
    networks:
      - hawai-net

  dify-db:
    image: postgres:15
    container_name: dify-db
    environment:
      POSTGRES_USER: dify
      POSTGRES_PASSWORD: dify
      POSTGRES_DB: dify
    volumes:
      - dify_db:/var/lib/postgresql/data
    networks:
      - hawai-net

  dify-redis:
    image: redis:6
    container_name: dify-redis
    networks:
      - hawai-net

  dify-plugin-daemon:
    image: langgenius/dify-plugin-daemon:latest
    container_name: dify-plugin-daemon
    env_file:
      - ./dify/docker/.env
    depends_on:
      - dify-api
      - dify-redis
    ports:
      - "5097:5097"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:5097/health" ]
      interval: 20s
      timeout: 5s
      retries: 30

  dify-worker:
    image: langgenius/dify-worker:latest
    container_name: dify-worker
    env_file:
      - ./dify/docker/.env
    depends_on:
      - dify-api
      - dify-redis
      - dify-db

  

volumes:
  ollama_models:
  dify_db:

networks:
  hawai-net:
    driver: bridge


