services:
  ollama:
    build:
      context: .
      dockerfile: Ollama.Dockerfile
    restart: unless-stopped
    ports:
      - "11434:8000"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 10
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./HawAI-backend
    environment:
      - MONGO_URL=mongodb://rwuser:Mu2190541%3F@124.243.175.197:8635,188.239.49.153:8635/test?authSource=admin
      - MONGO_DB=hawai
      - CORS_ORIGINS=http://localhost:5173
      - OAI_BASE_URL=http://ollama:8000/v1
      - OAI_MODEL=llava:7b
      - JWT_SECRET=change-me
    depends_on:
      - ollama
    ports:
      - "8000:8000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm ci && node node_modules/vite/bin/vite.js --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
    driver: local
  ollama_data:
    driver: local


