apiVersion: v1
kind: Secret
metadata:
  name: hawai-secrets
  namespace: hawai
type: Opaque
data:
  JWT_SECRET: Y2hhbmdlLW1l
  # Base64-encoded full connection string (password URL-encoded). Update as needed.
  # echo -n 'mongodb://rwuser:Mu2190541%3F@124.243.175.197:8635,188.239.49.153:8635/test?authSource=admin' | base64
  MONGO_URL: bW9uZ29kYjovL3J3dXNlcjpNdTIxOTA1NDElM0ZAMTI0LjI0My4xNzUuMTk3Ojg2MzUsMTg4LjIzOS40OS4xNTM6ODYzNS90ZXN0P2F1dGhTb3VyY2U9YWRtaW4=


