apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawai-backend
  labels:
    app: hawai-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hawai-backend
  template:
    metadata:
      labels:
        app: hawai-backend
    spec:
      containers:
      - name: hawai-backend
        image: swr.ap-southeast-3.myhuaweicloud.com/<namespace>/hawai-backend:cci
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URL
          value: "mongodb://rwuser:Mu2190541%3F@124.243.175.197:8635,188.239.49.153:8635/test?authSource=admin"
        - name: MONGO_DB
          value: "hawai"
        - name: CORS_ORIGINS
          value: "http://hawai-frontend:80"
        - name: JWT_SECRET
          value: "hawai-production-secret-key-2024"
        - name: JWT_ALG
          value: "HS256"
        - name: JWT_EXPIRE_MINUTES
          value: "10080"
        - name: OAI_BASE_URL
          value: "http://hawai-ollama:11434/v1"
        - name: OAI_MODEL
          value: "llava:7b"
        - name: APP_NAME
          value: "HawAI API"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hawai-backend
  labels:
    app: hawai-backend
spec:
  selector:
    app: hawai-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
